id: P010591
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-20 10:15:32.581501
source_metadata:
  id: bdr:W19639
  title: སྤྱོད་འཇུག་གི་འགྲེལ་པ་ཚིག་ཉུང་དོན་གསལ།
  author: ''
  volumes:
    0b02254ecdc14f1bb57fc355057d3f8d:
      image_group_id: I1KG10484
      title: ''
      volume_number: 1
      total_pages: 285
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
