id: I66254E52
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T05:05:12+00:00'
last_modified: '2022-06-08T16:05:33.447652+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W19639
  title: སྤྱོད་འཇུག་གི་འགྲེལ་པ་ཚིག་ཉུང་དོན་གསལ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '9395':
      image_group_id: I1KG10484
      title: ''
      total_pages: 285
      order: 1
      base_file: 9395.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
